ALTER TABLE profiles
  ADD COLUMN bio TEXT,
  ADD COLUMN show_bio TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN show_friends TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN show_listings TINYINT(1) NOT NULL DEFAULT 1;
