<?php
return [
    'build' => [
        'label' => 'Custom Build',
        'summary' => 'Plan a bespoke PC or workstation build with component sourcing.',
        'requirements' => [
            'brand_id' => true,
            'model_id' => true,
            'issue' => true,
            'serial' => false,
            'device_type' => false,
            'build' => true,
        ],
        'flow' => [
            'entry' => 'brand',
            'steps' => [
                'brand' => [
                    'component' => 'select',
                    'label' => 'Choose Base Brand',
                    'name' => 'brand_id',
                    'required' => true,
                    'placeholder' => 'Select brand',
                    'optionsSource' => 'brands',
                    'next' => 'model',
                ],
                'model' => [
                    'component' => 'select',
                    'label' => 'Choose Model or Series',
                    'name' => 'model_id',
                    'required' => true,
                    'placeholder' => 'Select model or series',
                    'optionsSource' => 'models',
                    'next' => 'build',
                ],
                'build' => [
                    'component' => 'options',
                    'inputType' => 'radio',
                    'label' => 'Is this a full custom build?',
                    'name' => 'build',
                    'required' => true,
                    'options' => [
                        ['value' => 'yes', 'label' => 'Yes, design and source everything', 'next' => 'issue'],
                        ['value' => 'no', 'label' => 'No, I need help with upgrades', 'next' => 'issue'],
                    ],
                    'next' => 'issue',
                ],
                'issue' => [
                    'component' => 'textarea',
                    'label' => 'Tell us about your build goals',
                    'name' => 'issue',
                    'required' => true,
                    'next' => 'attachments',
                ],
                'attachments' => [
                    'component' => 'file',
                    'label' => 'Attach inspiration or part lists (optional)',
                    'name' => 'photo',
                    'accept' => 'image/jpeg,image/png',
                    'required' => false,
                    'next' => null,
                ],
            ],
        ],
    ],
    'repair' => [
        'label' => 'Repair',
        'summary' => 'Fix hardware, screen, and component issues with certified technicians.',
        'requirements' => [
            'brand_id' => true,
            'model_id' => true,
            'issue' => true,
            'serial' => false,
            'device_type' => false,
        ],
        'flow' => [
            'entry' => 'brand',
            'steps' => [
                'brand' => [
                    'component' => 'select',
                    'label' => 'Choose Brand',
                    'name' => 'brand_id',
                    'required' => true,
                    'placeholder' => 'Select brand',
                    'optionsSource' => 'brands',
                    'next' => 'model',
                ],
                'model' => [
                    'component' => 'select',
                    'label' => 'Choose Model',
                    'name' => 'model_id',
                    'required' => true,
                    'placeholder' => 'Select model',
                    'optionsSource' => 'models',
                    'next' => 'issue',
                ],
                'issue' => [
                    'component' => 'textarea',
                    'label' => 'Describe the problem',
                    'name' => 'issue',
                    'required' => true,
                    'next' => 'serial',
                ],
                'serial' => [
                    'component' => 'input',
                    'type' => 'text',
                    'label' => 'Serial (optional)',
                    'name' => 'serial',
                    'required' => false,
                    'next' => 'attachments',
                ],
                'attachments' => [
                    'component' => 'file',
                    'label' => 'Add a photo (optional)',
                    'name' => 'photo',
                    'accept' => 'image/jpeg,image/png',
                    'required' => false,
                    'next' => null,
                ],
            ],
        ],
    ],
    'clean' => [
        'label' => 'Cleaning & Tune-Up',
        'summary' => 'Improve performance with deep cleanings, malware removal, and tune-ups.',
        'requirements' => [
            'brand_id' => true,
            'model_id' => true,
            'issue' => true,
            'serial' => false,
            'device_type' => false,
        ],
        'flow' => [
            'entry' => 'brand',
            'steps' => [
                'brand' => [
                    'component' => 'select',
                    'label' => 'Choose Brand',
                    'name' => 'brand_id',
                    'required' => true,
                    'placeholder' => 'Select brand',
                    'optionsSource' => 'brands',
                    'next' => 'model',
                ],
                'model' => [
                    'component' => 'select',
                    'label' => 'Choose Model',
                    'name' => 'model_id',
                    'required' => true,
                    'placeholder' => 'Select model',
                    'optionsSource' => 'models',
                    'next' => 'issue',
                ],
                'issue' => [
                    'component' => 'textarea',
                    'label' => 'Describe the cleaning or tune-up goals',
                    'name' => 'issue',
                    'required' => true,
                    'next' => 'attachments',
                ],
                'attachments' => [
                    'component' => 'file',
                    'label' => 'Add a photo (optional)',
                    'name' => 'photo',
                    'accept' => 'image/jpeg,image/png',
                    'required' => false,
                    'next' => null,
                ],
            ],
        ],
    ],
    'other' => [
        'label' => 'Other Help',
        'summary' => 'Request support for accessories, peripherals, or unique situations.',
        'requirements' => [
            'brand_id' => false,
            'model_id' => false,
            'issue' => true,
            'serial' => false,
            'device_type' => true,
        ],
        'flow' => [
            'entry' => 'device',
            'steps' => [
                'device' => [
                    'component' => 'input',
                    'type' => 'text',
                    'label' => 'Device Type',
                    'name' => 'device_type',
                    'required' => true,
                    'next' => 'issue',
                ],
                'issue' => [
                    'component' => 'textarea',
                    'label' => 'Describe the problem or request',
                    'name' => 'issue',
                    'required' => true,
                    'next' => 'attachments',
                ],
                'attachments' => [
                    'component' => 'file',
                    'label' => 'Add a photo (optional)',
                    'name' => 'photo',
                    'accept' => 'image/jpeg,image/png',
                    'required' => false,
                    'next' => null,
                ],
            ],
        ],
    ],
    'diagnose' => [
        'label' => 'Diagnose & Troubleshoot',
        'summary' => 'Work with a technician to triage unknown issues and pick the right follow-up.',
        'requirements' => [
            'brand_id' => false,
            'model_id' => false,
            'issue' => false,
            'serial' => false,
            'device_type' => false,
        ],
        'flow' => [
            'entry' => 'symptoms',
            'steps' => [
                'symptoms' => [
                    'component' => 'options',
                    'inputType' => 'checkbox',
                    'label' => 'Which symptoms are you seeing?',
                    'name' => 'symptoms[]',
                    'required' => true,
                    'allowMultiple' => true,
                    'options' => [
                        ['value' => 'no_power', 'label' => 'Device will not power on', 'next' => 'contact'],
                        ['value' => 'slow', 'label' => 'Everything feels unusually slow', 'next' => 'contact'],
                        ['value' => 'display', 'label' => 'Display flickers or goes blank', 'next' => 'contact'],
                        ['value' => 'overheat', 'label' => 'Device overheats or shuts down', 'next' => 'contact'],
                        ['value' => 'unknown', 'label' => 'Something else or intermittent', 'next' => 'contact'],
                    ],
                    'next' => 'contact',
                ],
                'contact' => [
                    'component' => 'options',
                    'inputType' => 'radio',
                    'label' => 'Preferred contact option',
                    'name' => 'contact_preference',
                    'required' => true,
                    'options' => [
                        ['value' => 'message', 'label' => 'Message me through the app', 'next' => 'details'],
                        ['value' => 'call', 'label' => 'Call me to walk through it', 'next' => 'details'],
                        ['value' => 'dropoff', 'label' => 'I will drop the device off', 'next' => 'attachments'],
                    ],
                    'next' => 'details',
                ],
                'details' => [
                    'component' => 'textarea',
                    'label' => 'Share any recent changes or details',
                    'name' => 'issue',
                    'required' => true,
                    'next' => 'attachments',
                ],
                'attachments' => [
                    'component' => 'file',
                    'label' => 'Attach photos or screenshots (optional)',
                    'name' => 'photo',
                    'accept' => 'image/jpeg,image/png',
                    'required' => false,
                    'next' => null,
                ],
            ],
        ],
    ],
];
